apiVersion: v1
data:
  config.yml: |
    # This is a simplified config where the rest of the
    # settings are omitted and will be set by default.
    # See config.yml for the full configuration options.
    config:
      bind: 0.0.0.0:25566
      servers:
        server-0: 10.43.198.95:25565
      try:
        - server-0
      status:
        motd: |
          \u00a7r                         \u00a7b\u2756 \u00a76\u00a7lCoffee\u00a75\u00a7lMC\u00a7b \u2756\u00a7r\n                         \u00a76\u00a7l Climbing Nation
    connect:
      enabled: true
      name: coffee
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: gate
  name: gate-config
