apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: gate
  name: gate
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: proxy
        app.kubernetes.io/name: gate
    spec:
      containers:
      - image: ghcr.io/minekube/gate:latest
        name: gate
        ports:
        - containerPort: 25566
          name: minecraft
        volumeMounts:
        - mountPath: ./config.yml
          name: config
          subPath: config.yml
        - mountPath: ./connect.json
          name: token
          subPath: connect.json
          readOnly: false
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      volumes:
      - configMap:
          name: gate-config
        name: config
      - secret:
          secretName: connector-token
        name: token
