apiVersion: v1
data:
    token.json: ENC[AES256_GCM,data:BTBn60FSsY2UDGX4YlrWAZAIURSaXJd0gxwdtzza0EbS+ohP+ht/SA==,iv:vzYP+dmT7DdppMAGU5OCd99VmoN35QQNG3Vo7xgXEos=,tag:ZdIHV9l3bHYTQ08bA5bjUA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m74ukye349p80duvy953d7vrpzvd60jx0vr49ew5df2rg2aj4u2sjpuv25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR0oraWJXd0Fpcncvd0Z3
            MnFUcVBXdWpJeG1Td0FObGM3cDFuL2liblVJCjBNbjBKVW1PcmpJV1d3M21wbVBh
            bVFzQzFaVWZzRXh3R0tpcHUzNlJQNFUKLS0tIFd6ZFNoZksrK3EyYXJ2Nkg4dnl0
            dXVGL3NIcmw5dkNyQXU5SGdITW5xOW8KKu4MGPWsq1qRgqu4sBjzxHCuGWThP+M2
            4+vjI47aZe65IJcqCOYEhISmlnB2mdldQ5G5xCd+xS+amZgUKMAAeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T06:32:30Z"
    mac: ENC[AES256_GCM,data:VvllPCe6mUdCT+oBwuuciNFtcqr3+m9yhETHFter8t8BEKPD1AtGl///UbiLfDasMANpk13tmhLUZQ4AC+YpgO8dnQX610++IzV76k8De6o1mIzFaTjccQXFRhT0kGzyFD8GCdLbNucQeBUGcFxXlbVa1DTeB6iGAHHHT/S5h1k=,iv:VaYoZDQI2lRj8sl0oWibBR7JbPYJ/3hML+zbqpD0gtY=,tag:Hjx9BnZ299DeQGRyCOyicw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
