apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 0 # volume group ID
        runAsUser: 1000 # node user ID
        runAsGroup: 1000 # node group ID
      containers:
        - name: audiobookshelf
          image: advplyr/audiobookshelf:2.17.3
          envFrom:
            - configMapRef:
                name: audio-configmap
          volumeMounts:
            - mountPath: /config
              name: audiobookshelf-data
            - mountPath: /metadata
              name: audiobookshelf-data
            - mountPath: /audiobooks
              name: audiobookshelf-data
            - mountPath: /podcasts
              name: audiobookshelf-data
      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
